# -*- mode: ruby -*-
# vi set ft=ruby:

# Vagranfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|

 # by default we use a 64 box
 config.vm.box = "hashicorp/precise64"

 # but this does not seem to work on a 32-bit Windoze 
 #if ENV["PROCESSOR_ARCHITECTURE"] == "x86"
 #  puts "falling back to 32-bit guest architecture"
 #  config.vm.box = "hashicorp/precise32"
 #end

 # common stuff (32 and 64 bit)
 config.vm.provision "docker"
 config.vm.provision "shell", inline:
   "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
end
