# -*- mode: ruby -*-
# vi set ft=ruby:

# Vagranfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure("2") do |config|
 config.vm.box = "precise64"
 config.vm.provision "docker"
 config.vm.provision "shell", inline:
   "ps aux | grep 'sshd:' | awk '{print $2}' | xargs kill"
end
